name: Production

on:
  push:
    branches: [ fc-production ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Pull code on server
        uses: appleboy/ssh-action@v0.0.7
        with:
          host: ${{ secrets.PRODUCTION_HOST }}
          username: ${{ secrets.PRODUCTION_USER }}
          password: ${{ secrets.PRODUCTION_PASSWORD }}
          port: ${{ secrets.PRODUCTION_PORT }}
          script: cd www; git pull origin fc-production
