name: Staging

on:
  push:
    branches: [ fc-staging ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Pull code on server
        uses: appleboy/ssh-action@v0.0.7
        with:
          host: ${{ secrets.host }}
          username: ${{ secrets.user }}
          password: ${{ secrets.password }}
          port: ${{ secrets.port }}
          script: cd chamilo; git pull origin fc-staging --rebase
